#######
# Cloudify OpenStack & Bash hello world.
#

imports:
    - cloudify.bash
    - cloudify.openstack

types:
    cloudify.types.bash.web_server_with_index_and_image:
        derived_from: cloudify.types.bash.web_server
        properties:
            - image_path
            - index_path

blueprint:
    name: hello_world
    nodes:
        -   name: virtual_ip
            type: cloudify.openstack.floatingip
            properties:
                floatingip: 
                    floating_network_name: Ext-Net

        -   name: security_group
            type: cloudfiy.openstack.security_group
            properties:
                security_group:
                    name: webserver_security_group
                rules:
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 8080            

        -   name: vm
            type: cloudify.openstack.server
            instances:
                deploy: 1
            properties:
                install_agent: true
                server:
                    name: bash-web-server
                    image: 8c096c29-a666-4b82-99c4-c77dc70cfb40
                    flavor: 102
                    security_groups: ['default', 'allPorts']
            relationships:
                -   type: cloudify.openstack.server_connected_to_floating_ip
                    target: virtual_ip
                -   type: cloudify.relationships.connected_to
                    target: security_group                    


        -   name: http_web_server
            type: cloudify.types.bash.web_server_with_index_and_image
            properties:
                port: 8080
                image_path: images/cloudify-logo.png
                index_path: index.html
                scripts:            
                    configure: scripts/configure.sh
                    start: scripts/start.sh
                    stop: scripts/stop.sh
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: vm
                    